#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rcssmin
Version  : 1.0.6
Release  : 4
URL      : https://pypi.python.org/packages/source/r/rcssmin/rcssmin-1.0.6.tar.gz
Source0  : https://pypi.python.org/packages/source/r/rcssmin/rcssmin-1.0.6.tar.gz
Summary  : CSS Minifier
Group    : Development/Tools
License  : Apache-2.0
Requires: rcssmin-python
Requires: rcssmin-doc
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
These test inputs are originally taken from the YUI compressor suite
(https://github.com/yui/yuicompressor/). The outputs (in the out/ directory) are
my own.

%package doc
Summary: doc components for the rcssmin package.
Group: Documentation

%description doc
doc components for the rcssmin package.


%package python
Summary: python components for the rcssmin package.
Group: Default

%description python
python components for the rcssmin package.


%prep
%setup -q -n rcssmin-1.0.6

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/rcssmin/*

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
