#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rcssmin
Version  : 1.0.6
Release  : 27
URL      : https://files.pythonhosted.org/packages/e2/5f/852be8aa80d1c24de9b030cdb6532bc7e7a1c8461554f6edbe14335ba890/rcssmin-1.0.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/e2/5f/852be8aa80d1c24de9b030cdb6532bc7e7a1c8461554f6edbe14335ba890/rcssmin-1.0.6.tar.gz
Summary  : CSS Minifier
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: rcssmin-license = %{version}-%{release}
Requires: rcssmin-python = %{version}-%{release}
Requires: rcssmin-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
CSS Minifier
        ==============
        
        RCSSmin is a CSS minifier.
        
        The minifier is based on the semantics of the `YUI compressor`_\, which itself
        is based on `the rule list by Isaac Schlueter`_\.
        
        This module is a re-implementation aiming for speed instead of maximum
        compression, so it can be used at runtime (rather than during a preprocessing
        step). RCSSmin does syntactical compression only (removing spaces, comments
        and possibly semicolons). It does not provide semantic compression (like
        removing empty blocks, collapsing redundant properties etc). It does, however,
        support various CSS hacks (by keeping them working as intended).

%package doc
Summary: doc components for the rcssmin package.
Group: Documentation

%description doc
doc components for the rcssmin package.


%package license
Summary: license components for the rcssmin package.
Group: Default

%description license
license components for the rcssmin package.


%package python
Summary: python components for the rcssmin package.
Group: Default
Requires: rcssmin-python3 = %{version}-%{release}

%description python
python components for the rcssmin package.


%package python3
Summary: python3 components for the rcssmin package.
Group: Default
Requires: python3-core
Provides: pypi(rcssmin)

%description python3
python3 components for the rcssmin package.


%prep
%setup -q -n rcssmin-1.0.6
cd %{_builddir}/rcssmin-1.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1603403257
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rcssmin
cp %{_builddir}/rcssmin-1.0.6/LICENSE %{buildroot}/usr/share/package-licenses/rcssmin/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/rcssmin-1.0.6/bench/LICENSE.cssmin %{buildroot}/usr/share/package-licenses/rcssmin/2c0343517b99ae17764c408b6313ea09d921a856
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/rcssmin/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rcssmin/2c0343517b99ae17764c408b6313ea09d921a856
/usr/share/package-licenses/rcssmin/7df059597099bb7dcf25d2a9aedfaf4465f72d8d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
